question_data = {"response_code": 0, "results": [{"category": "Vehicles", "type": "boolean", "difficulty": "hard",
                                                  "question": "In 1993 Swedish car manufacturer Saab experimented with replacing the steering wheel with a joystick in a Saab 9000.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Science: Computers", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "The name of the main character of the video game &quot;The Legend of Zelda&quot;, is Zelda.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Celebrities", "type": "boolean", "difficulty": "medium",
                                                  "question": "Michael Jackson had a pet python named &lsquo;Crusher&rsquo;.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                                  "question": "The Republic of Malta is the smallest microstate worldwide.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Film", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Science & Nature", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "The planet Mars has two moons orbiting it.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Film", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "There aren&#039;t any live-action clones in &quot;Star Wars: Episode III - Revenge of the Sith&quot;.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Science: Computers", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Linus Torvalds created Linux and Git.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                                                  "question": "Kangaroos keep food in their pouches next to their children.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Science: Computers", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Science & Nature", "type": "boolean",
                                                  "difficulty": "hard",
                                                  "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Japanese Anime & Manga",
                                                  "type": "boolean", "difficulty": "medium",
                                                  "question": "The animated film &quot;Spirited Away&quot; won the Academy Award for Best Animated Feature at the 75th Academy Awards in 2003.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "History", "type": "boolean", "difficulty": "easy",
                                                  "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Science & Nature", "type": "boolean",
                                                  "difficulty": "easy", "question": "An atom contains a nucleus.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Science: Computers", "type": "boolean",
                                                  "difficulty": "medium", "question": "MacOS is based on Linux.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "In World of Warcraft lore, Thrall is the original wielder of &quot;Doomhammer&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "hard",
                                                  "question": "In &quot;Portal 2&quot;, Cave Johnson started out Aperture Science as a shower curtain company.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "In &quot;Super Mario 3D World&quot;, the Double Cherry power-up originated from a developer accidentally making two characters controllable.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series&#039; history.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "History", "type": "boolean", "difficulty": "medium",
                                                  "question": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Animals", "type": "boolean", "difficulty": "medium",
                                                  "question": "The average lifespan of a wildcat is only around 5-6 years. ",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Science: Gadgets", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "The Western Electric Model 500 telephone uses tone dialing to dial phone numbers.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                                  "question": "Toronto is the capital city of the North American country of Canada.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "History", "type": "boolean", "difficulty": "hard",
                                                  "question": "The Battle of Trafalgar took place on October 23rd, 1805",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Science: Computers", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "The Windows 7 operating system has six main editions.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Politics", "type": "boolean", "difficulty": "medium",
                                                  "question": "George W. Bush lost the popular vote in the 2004 United States presidential election.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "Japan has left-hand side traffic.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "General Knowledge", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                                                  "question": "One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was &quot;Yes We Can&quot;.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Music", "type": "boolean",
                                                  "difficulty": "easy", "question": "Daft Punk originated in France.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Music", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Stevie Wonder&#039;s real name is Stevland Hardaway Morris.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "In Rocket League, you can play Basketball.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Board Games", "type": "boolean",
                                                  "difficulty": "hard",
                                                  "question": "The board game Go has more possible legal positions than the number of atoms in the visible universe.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Mythology", "type": "boolean", "difficulty": "medium",
                                                  "question": "The Roman god &quot;Jupiter&quot; was first known as &quot;Zeus&quot; to the Greeks.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Celebrities", "type": "boolean", "difficulty": "hard",
                                                  "question": "Lady Gaga&#039;s real name is Stefani Joanne Angelina Germanotta.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Music", "type": "boolean",
                                                  "difficulty": "hard",
                                                  "question": "Pete Townshend&#039;s solo album, &quot;White City: A Novel&quot;, is set in the metropolitan area of Chicago.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Books", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "&quot;Green Eggs and Ham&quot; consists of only 50 different words.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                                                  "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "Donald Duck played the role of Bob Cratchit in Disney&#039;s 1983 adaptation of A Christmas Carol.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                                  "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Doki Doki Literature Club was developed in Japan.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Science & Nature", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "&quot;Tachycardia&quot; or &quot;Tachyarrhythmia&quot; refers to a resting heart-rate near or over 100 BPM.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]}]}
